# Generated by Django 5.1.3 on 2024-12-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='customer_feedbacks/customer_images')),
                ('name', models.CharField(max_length=500)),
                ('profession', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='categories/category_icons')),
                ('name', models.CharField(max_length=500)),
                ('course_counts', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='courses/course_thumbnails')),
                ('title', models.CharField(max_length=500)),
                ('course_description', models.TextField()),
                ('author', models.CharField(max_length=500)),
                ('rating_star', models.ImageField(upload_to='courses/course_rating_stars')),
                ('rating_single_star', models.ImageField(upload_to='courses/course_rating_stars')),
                ('rating_five_out_of', models.CharField(max_length=500)),
                ('rating_text', models.CharField(max_length=500)),
                ('course_hours', models.CharField(max_length=500)),
                ('lecture_counts', models.CharField(max_length=500)),
                ('course_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=50)),
                ('author_icon', models.ImageField(upload_to='courses/course_authors')),
                ('course_languages', models.CharField(max_length=500)),
                ('course_detail_thumbnail', models.ImageField(upload_to='courses/course_detail_thumbnails')),
                ('price', models.CharField(max_length=500)),
                ('strike_out_price', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_image', models.ImageField(upload_to='instructors/instructor_images')),
                ('name', models.CharField(max_length=500)),
                ('course_name', models.CharField(max_length=500)),
                ('rating_star', models.ImageField(upload_to='instructors/rating_stars')),
                ('rating_text', models.CharField(max_length=500)),
                ('students_enrolled_count', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='web.top_courses')),
            ],
        ),
    ]
